### PR TITLE
Build a new layout

### PR DESCRIPTION
**Pull request by powilliam**
As i said in my last PR, i've worked on a new design so here we go

## Changes
1. Create a new Screen and navigate to it when the timer reaches 25 minutes
2. Use the Hooks API, especially the ```useEffect``` to set the new time elapsed each second and clear the interval every time when a registered dependency suffer an update
3. Use other Lottie Animation because the new Expo SDK still in Alpha so unfortunately we cannot use animations from the recent Bodymovin version because the Expo uses lottie-react-native v2. It was hard to find, but i think that this is better than the older one :sweat_smile:
4. Use  ```TransitionSpecs``` based on the current Platform and ```TransitionPresets.SlideFromRightIOS``` from ```React Navigation```

## Issues
- There's a little user experience issue when doing a back navigation. When clicking in "I'm ready to work again" (Congrats Screen) and navigating to the Timer screen, the navigation history isn't cleaned. So if user does a back navigation he will navigate to Congrats again. I didn't implement a fix because i need to read more about how ```React Navigation``` handle with its navigation API

## Possible features
- Let the user set the work interval and the rest interval.
- Use ```TypeORM``` with ```expo-sqlite``` to record his usage and show as his progress. Why not use a chart? "Easy like that", as you say :stuck_out_tongue: 

## Ladies and Gentleman! :scream:  :rocket: :purple_heart: 

ezgif com-video-to-gif

### CODE REVIEW

**Comment by diego3g** [comment]
WTF! 😮😮

**Review by diego3g — APPROVED** [review]
Great job, i'll just run this tomorrow to make sure everything is ok as we do not have any tests yet and then i'll merge it.

**Comment by powilliam** [comment]
Sure and thanks. Can you give me a feedback about how it looks on IOS?

**Comment by diego3g** [comment]
@powilliam it looks all cool in iOS, nothing that should be changed :) Thanks again.

**Pull request merged**
